### ISSUE TITLE
The content of $OFS variable can break the Invoke-Template script

### ISSUE THREAD

**Issue by LaurentDardenne** [dfinke/powershell-for-developers#1]
Hi,
the content of $OFS variable can break the Invoke-Template script (/chapter04/InvokeTemplate/Invoke-Template.ps1)

Example :
$ofs=','
.\Test-CodeAST.ps1

Add-Type : c:\Users\Laurent\AppData\Local\Temp\ihdr1pnm.0.cs(23): Jeton ',' non valide dans la déclaration de membres de la classe, de la structure ou de l'interface
c:\Users\Laurent\AppData\Local\Temp\ihdr1pnm.0.cs(22) :     }
c:\Users\Laurent\AppData\Local\Temp\ihdr1pnm.0.cs(23) : >>>  ,
c:\Users\Laurent\AppData\Local\Temp\ihdr1pnm.0.cs(24):     public override AstVisitAction
VisitErrorExpression(ErrorExpressionAst ast)
Au caractère G:\PS\AST\chapter04\InvokeTemplate\Test-CodeAST.ps1:1 : 1
- Add-Type (.\CodeAst.ps1)

**Comment by dfinke** [comment]
Thanks for reporting that issue.

Off the top of my head, wrapping the `& $ScriptBlock` in `Invoke-Template.ps1` like below can solve that. I need to think through if this is the best approach.

``` powershell
$saveOFS = $OFS
$OFS=$null
& $ScriptBlock
$OFS = $saveOFS
```
